- name: Build data import image
  docker_image:
    path: "{{ base_dir }}/packages/models"
    dockerfile: "{{ base_dir }}/dockerfiles/importer.Dockerfile"
    name: pp/importer
    tag: latest
    state: present
    force: yes
  become: yes
  tags:
    - build_data_import_image

- name: Install p7zip
  yum:
    name: p7zip
  become: yes
  tags:
    - install_7zip

- name: Download data file
  get_url:
    url: "{{ data_url }}"
    dest: "{{ base_dir }}/{{ data_file_name }}"
    mode: 0664
  tags:
    - download_file
    - data_import

- name: Extract all files
  command: "7za x {{ base_dir }}/{{ data_file_name }}"
  tags:
    - extract_archive
    - data_import

- name: Start import
  docker_container:
    name: "data_importer"
    image: "pp/importer:latest"
    state: started
    recreate: yes
    networks:
      - name: pp_net
    volumes:
      - "{{ data_import_path_name }}:/app/data:Z"
    command: "python importer.py --path /app/data --class_name 44fz"
    env:
      POSTGRES_USER: "{{ postgres_user }}"
      POSTGRES_PASSWORD: "{{ postgres_password }}"
      POSTGRES_DATABASE: "{{ postgres_db }}"
      POSTGRES_HOST: "{{ postgres_host }}"
  become: yes
  tags:
    - import_container
    - data_import
